version: '3.7'

services:

  channel_sender:
    build:
      context: ./channel_sender
    image: localhost:5000/channel_sender
    networks:
      - kafka
      - digital-comms
    volumes:
      - type: bind
        source: /mnt/swarm-shared/joncatlin-development/repos/poc-dc/channel_sender/templates
        target: /home/docker-user/templates
        read_only: true
      - type: bind
        source: /mnt/swarm-shared/joncatlin-development/repos/poc-dc/channel_sender/pdf-output
        target: /home/docker-user/pdf-output
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka1:19092,kafka2:19092,kafka3:19092
      - KAFKA_CONSUMER_TOPIC=dc-msgs
      - KAFKA_PRODUCER_TOPIC=dc-events
      - KAFKA_GROUP_ID=channel-sender
      - PDF_SERVICE_URL=http://make_pdf:3000/convert/html
# Needed to debug stuff
      - RUST_BACKTRACE=full
      - RUST_LOG=channel_sender=info
# SEND_TO_VENDOR toggles whether to send real msgs to the vendor or skip that action
# Used during performance testing to not incur charges with vendors
      - SEND_TO_VENDOR=false
    secrets:
      - sms_vendor_account_id
      - sms_vendor_token
      - email_vendor_token

networks:
  kafka:
    external: true
  digital-comms:
    external: true


secrets:
  sms_vendor_account_id:
    external: true
  sms_vendor_token:
    external: true
  email_vendor_token:
    external: true
