version: '3.7'

services:

  dc-router:
    build:
      context: ./dc-router
    image: localhost:5000/dc-router
    ports:
      - "50014:8080"
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka1:19092,kafka2:19092,kafka3:19092
      - KAFKA_TOPIC=dc-msgs
      - RUST_BACKTRACE=full
      - RUST_LOG=debug
    networks:
      - kafka

networks:
  kafka:
    external: true
