version: '3.7'

services:

  test:
    build:
      context: ./diesel-example
    image: localhost:5000/diesel-example
    ports:
      - "8086:8080"
    networks:
      - event-db

networks:
  event-db:
    external: true
