version: '3.7'

services:

  webhooks:
    build:
      context: ./webhooks
    image: webhooks
    ports:
      - "50012:8081"
    networks:
      - webhooks
      - zoo_net

  event-store:
    build:
      context: ./event-store
    image: event-store
    networks:
      - zoo_net

networks:
  webhooks:
    driver: overlay
  zoo_net:
    driver: overlay


# secrets:
#   db_password:
#     file: ./sql/db_password.txt
