version: '3.7'

services:

  webhooks:
    build:
      context: ./webhooks
#      dockerfile: ./webhooks/Dockerfile
    image: webhooks
    ports:
      - "50012:8081"
    networks:
      - webhooks
      - zoo_net

networks:
  webhooks:
    driver: overlay
  zoo_net:
    driver: overlay


# secrets:
#   db_password:
#     file: ./sql/db_password.txt
