version: '3.7'

services:

  event-store:
    build:
      context: ./event-store
    image: localhost:5000/event-store
    environment:
      - KAFKA_BOOTSTRAP_SERVERS="kafka1:19092,kafka2:19092,kafka3:19092"
      - KAFKA_TOPIC="events"
      - KAFKA_GROUP_ID="event_store"
    networks:
      - zoo_net

networks:
  webhooks:
    driver: overlay
  zoo_net:
    driver: overlay