# TODO
# 1. Secrets for Postgres username, password
version: "3.7"

services:

  event-db:
    image: postgres:11-alpine
    environment:
      POSTGRES_DB_FILE: /run/secrets/postgres_db
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_USER_FILE: /run/secrets/postgres_user
    volumes:
      # Persist content outside of the container
      - type: bind
        source: /mnt/swarm-shared/joncatlin-development/shared-volumes/poc-dc/postgres
        target: /var/lib/postgresql/data
    ports:
      - "55432:5432"
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
#        delay: 30s
      restart_policy:
        condition: any
      resources:
        limits:
          cpus: '1'
          memory: 1024M
        reservations:
          cpus: '1'
          memory: 512M
    networks:
      - event-db
    secrets:
      - postgres_db
      - postgres_user
      - postgres_password


  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: joncatlin
      PGADMIN_DEFAULT_PASSWORD: password
#      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: "True"
      PGADMIN_CONFIG_LOGIN_BANNER: '"Authorised users only!"'
      PGADMIN_CONFIG_CONSOLE_LOG_LEVEL: 10
    ports:
      - "8082:80"
    networks:
      - event-db

networks:
  event-db:
    external: true

secrets:
  postgres_db:
    external: true
  postgres_user:
    external: true
  postgres_password:
    external: true
