version: '3.7'

services:

  test_channel_sender:
    build:
      context: ./test_channel_sender
    image: localhost:5000/test_channel_sender
    secrets:
      - account_id
      - token
    networks:
      - kafka
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka1:19092,kafka2:19092,kafka3:19092
      - KAFKA_TOPIC=dc-msgs
      - RUST_BACKTRACE=full
      - RUST_LOG=debug

    command: -b 2 -m 3 -c email

networks:
  kafka:
    external: true


secrets:
  account_id:
    external: true
  token:
    external: true
