version: '3.7'

services:

  ui-services:
    build:
      context: ./ui-services
    image: localhost:5000/ui-services
    environment:
      - DATABASE_URL=postgres://event_user:event_pwd@event-db:5432/events
    networks:
      - event-db
    ports:
      - "50012:8080"
#      - "8085:8080"

networks:
  event-db:
    external: true
