version: '3.7'

services:

  ui-services:
    build:
      context: ./ui-services
    image: localhost:5000/ui-services
    environment:
      - DATABASE_URL=postgres://event_user:event_pwd@event-db:5432/events
      - RUST_BACKTRACE=full
      - RUST_LOG=ui_services=debug
    networks:
      - event-db
    ports:
      - "50013:8080"
#      - "8085:8080"
    volumes:
    - type: bind
      source: /mnt/swarm-shared/joncatlin-development/repos/poc-dc/ui-services/template-temp
      target: /home/docker-user/template_temp

networks:
  event-db:
    external: true
