version: '3.7'

services:

  webhooks:
    build:
      context: ./webhooks
    image: localhost:5000/webhooks
    ports:
      - "50012:8081"
    environment:
      - KAFKA_BOOTSTRAP_SERVERS="kafka1:19092,kafka2:19092,kafka3:19092"
      - KAFKA_TOPIC="events"
    networks:
      - kafka

networks:
  kafka:
    external: true
